function generatePlaywrightSelectors(a){if(!a)throw Error("Please provide a valid DOM element");const c=[],d=analyzeElementContext(a);generateAllSelectors(a,c,d);d.isInShadowRoot?c.sort((b,f)=>{var k=b.selector.includes("locator('#")||b.selector.includes('locator("#'),l=f.selector.includes("locator('#")||f.selector.includes('locator("#');if(k&&!l)return-1;if(!k&&l)return 1;k=b.selector.includes("locator(")&&!b.selector.includes("getBy")&&!b.selector.includes("//")&&!b.selector.includes(":has-text");
l=f.selector.includes("locator(")&&!f.selector.includes("getBy")&&!f.selector.includes("//")&&!f.selector.includes(":has-text");return k&&!l?-1:!k&&l?1:b.count-f.count}):c.sort((b,f)=>b.count-f.count);return c}
function convertJavaToJavaScript(a){if(!a.includes("AriaRole.")&&!a.includes(".set")&&!a.includes("new ")&&a.includes("page."))return a;a=a.replace(/getByRole\(AriaRole\.(\w+)\.setName\((["'])([^"']+)\2\)\)/g,(c,d,b,f)=>`getByRole('${d.toLowerCase()}', { name: '${f.replace(/'/g,"\\'")}' })`);a=a.replace(/getByRole\(AriaRole\.(\w+)\)(?!\.)/g,(c,d)=>`getByRole('${d.toLowerCase()}')`);a=a.replace(/getByRole\(AriaRole\.(\w+),\s*new\s+Page\.GetByRoleOptions\(\)((?:\.\w+\([^)]*\))+)\)/g,(c,d,b)=>{c=parseJavaOptionChain(b);
c=Object.entries(c).map(([f,k])=>`${f}: ${k}`).join(", ");return`getByRole('${d.toLowerCase()}', { ${c} })`});a=a.replace(/(getBy(?:Text|Label|Placeholder|Title|AltText))\((["'])([^"']+)\2,\s*new\s+Page\.\w+Options\(\)((?:\.\w+\([^)]*\))+)\)/g,(c,d,b,f,k)=>{c=parseJavaOptionChain(k);c=Object.entries(c).map(([l,t])=>`${l}: ${t}`).join(", ");return`${d}('${f.replace(/'/g,"\\'")}', { ${c} })`});a=a.replace(/(getBy(?:Text|Label|Placeholder|Title|AltText|TestId))\((["'])([^"']+)\2\)/g,(c,d,b,f)=>`${d}('${f.replace(/'/g,
"\\'")}')`);return a.trim().startsWith("page")?a:"page."+a.replace(/^\.+/,"")}function parseJavaOptionChain(a){const c={};a=a.matchAll(/\.set(\w+)\(([^)]+)\)/g);for(const b of a){var d=b[1];a=b[2].trim();d=d.charAt(0).toLowerCase()+d.slice(1);"true"===a||"false"===a?c[d]=a:a.match(/^["'](.+?)["']$/)?(a=a.slice(1,-1),c[d]=`'${a.replace(/'/g,"\\'")}'`):(a.match(/^\d+$/),c[d]=a)}return c}
function countSelectorMatches(a){try{a=convertPythonToJavaScript(a);a=convertJavaToJavaScript(a);a=normalizeLegacyOperators(a);if(!validateSelectorSyntax(a).isValid)return 0;const c=parseSelectorContext(a);let d=navigateToContext(c);if(!d)return 0;const b=extractCleanSelector(a);if(b.includes("frameLocator")){const f=b.split(/\.frameLocator\([^)]+\)/);return executeCount("page"+f[f.length-1],d)}return executeCount(b,d)}catch(c){return console.error("Error in countSelectorMatches:",c),0}}
function normalizeLegacyOperators(a){if(!a.includes(">>"))return a;var c=a.match(/page\.locator\(["'`]([^"'`]+)["'`]\)/);if(!c)return a;c=c[1].split(">>").map(b=>b.trim());if(1===c.length)return a;let d="page";c.forEach((b,f)=>{b.startsWith("text=")?(b=b.substring(5),d+=`.getByText('${b}')`):d+=`.locator('${b}')`});return d}
function validateSelectorSyntax(a){if(!a.trim().startsWith("page"))return{isValid:!1,error:'Selector must start with "page" (e.g., page.locator(...) or page.getByRole(...))'};if(a.includes(">>"))return{isValid:!1,error:'Legacy >> operator detected. Use modern chaining: page.locator("div").locator("text=Company") or page.locator("div").filter({ hasText: "Company" })'};const c=[];var d=(a.match(/'/g)||[]).length,b=(a.match(/"/g)||[]).length;const f=(a.match(/`/g)||[]).length;0!==d%2&&c.push("Unclosed single quote (')");
0!==b%2&&c.push('Unclosed double quote (")');0!==f%2&&c.push("Unclosed backtick (`). Template literals must be closed with a matching backtick.");d=(a.match(/\(/g)||[]).length;b=(a.match(/\)/g)||[]).length;d!==b&&(d>b?c.push(`Missing ${d-b} closing parenthesis${1<d-b?"es":""} ")"`):c.push(`Extra ${b-d} closing parenthesis${1<b-d?"es":""} ")"`));d=(a.match(/\[/g)||[]).length;b=(a.match(/\]/g)||[]).length;d!==b&&(d>b?c.push(`Missing ${d-b} closing bracket${1<d-b?"s":""} "]"`):c.push(`Extra ${b-d} closing bracket${1<
b-d?"s":""} "]"`));d=(a.match(/\{/g)||[]).length;b=(a.match(/\}/g)||[]).length;d!==b&&(d>b?c.push(`Missing ${d-b} closing brace${1<d-b?"s":""} "}"`):c.push(`Extra ${b-d} closing brace${1<b-d?"s":""} "}"`));const k="getByRole getByText getByLabel getByPlaceholder getByAltText getByTitle getByTestId locator frameLocator filter nth first last and or".split(" ");d=/\.([\w]+)\(/g;b=[];let l;for(;null!==(l=d.exec(a));)b.push(l[1]);d=b.filter(t=>!k.includes(t));0<d.length&&c.push(`Invalid Playwright method(s): ${d.join(", ")}. Valid methods: ${k.join(", ")}`);
a.includes("locator`")&&(d=a.match(/locator`/g),b=a.substring(a.indexOf("locator`")+7).includes("`"),d&&!b&&c.push("Template literal in locator` is not closed. Add a closing backtick (`) at the end."));if(a.includes("//")||a.includes("//*"))if((d=a.match(/locator`([^`]+)`/))||(d=a.match(/locator\('([^']+)'\)/)),d||=a.match(/locator\("([^"]+)"\)/),d&&d[1]){if(d=d[1],d.startsWith("//")||d.startsWith("//*"))try{document.evaluate(d,document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null)}catch(t){c.push(`Invalid XPath: ${t.message}`)}}else a.includes("//")&&
c.push("Could not parse XPath. Check that the locator string is properly formatted.");if(a.includes("locator")&&((d=a.match(/locator`([^`]+)`/))||(d=a.match(/locator\('([^']+)'\)/)),d||=a.match(/locator\("([^"]+)"\)/),d&&d[1])){const t=d[1];d=":has-text( :text-is( :text( :has( :is( :visible :hidden".split(" ").some(q=>t.includes(q));if(!t.startsWith("//")&&!t.startsWith("//*")&&!d)try{document.querySelector(t)}catch(q){c.push(`Invalid CSS selector: ${q.message}`)}}a.includes(".filter(")&&(a.match(/\.filter\(\s*\{/)||
c.push('Invalid filter syntax. Expected: .filter({ hasText: "..." }) or .filter({ has: ... })'));0!==f%2&&a.includes("locator`")&&(a=a.includes("//")?"page.locator`//tr[td[contains(., 'text')]]//button`":"page.locator`.my-class`",c.push(`Example of correct template literal syntax: ${a}`));return 0<c.length?{isValid:!1,error:c.join("\n\u2022 ")}:{isValid:!0,error:null}}
function parseSelectorContext(a){const c={iframeSelectors:[],shadowSelectors:[],hasIframe:!1,hasShadow:!1,mixedChain:[]},d=[];var b=/\.(frameLocator|locator)\('([^']*)'\)/g;let f;for(;null!==(f=b.exec(a));)d.push({type:f[1],selector:f[2],index:f.index,lastIndex:b.lastIndex});for(b=/\.(frameLocator|locator)\("([^"]*)"\)/g;null!==(f=b.exec(a));)d.push({type:f[1],selector:f[2],index:f.index,lastIndex:b.lastIndex});for(b=/\.(frameLocator|locator)`([^`]*)`/g;null!==(f=b.exec(a));)d.push({type:f[1],selector:f[2],
index:f.index,lastIndex:b.lastIndex});d.sort((k,l)=>k.index-l.index);d.forEach((k,l)=>{"frameLocator"===k.type&&(c.iframeSelectors.push(k.selector),c.hasIframe=!0,c.mixedChain.push({type:"iframe",selector:k.selector}))});return c}
function navigateToContext(a){let c=document;if(a.mixedChain&&0<a.mixedChain.length){for(const d of a.mixedChain)try{if("shadow"===d.type){const b=querySelectorAllDeep(d.selector,c)[0];if(!b||!b.shadowRoot)return null;c=b.shadowRoot}else if("iframe"===d.type){const b=querySelectorAllDeep(d.selector,c)[0];if(!b)return null;c=b.contentDocument||b.contentWindow?.document;if(!c)return null}}catch(b){return null}return c}if(a.hasIframe)for(const d of a.iframeSelectors)try{const b=querySelectorAllDeep(d,
c)[0];if(!b)return null;c=b.contentDocument||b.contentWindow?.document;if(!c)return null}catch(b){return null}return c}
function extractCleanSelector(a){a=a.replace(/^page\./,"");if(a.includes(".filter(")||a.match(/\.(first|last|nth)\(/)||a.includes("frameLocator"))return"page."+a;var c=a.match(/\.locator\([^)]+\)/g),d=a.match(/\.(getByText|getByRole|getByLabel)\([^)]+\)/g);if(c&&1<c.length||d)return"page."+a;c=a.match(/(getBy[A-Za-z]+\(.+\))$/);d=a.match(/locator\((['"`])(.+?)\1\)(?!.*locator)/);if(c)return"page."+c[1];if(d)return"page.locator("+d[1]+d[2]+d[1]+")";c=Array.from(a.matchAll(/locator\((['"`])(.+?)\1\)/g));
return 0<c.length?(a=c[c.length-1],"page.locator("+a[1]+a[2]+a[1]+")"):a.startsWith("page.")?a:"page."+a}
function analyzeElementContext(a){const c={isInIframe:!1,iframeChain:[],isInShadowRoot:!1,shadowHosts:[],isSvgElement:!1,rootDocument:a.ownerDocument,mixedContext:[]};"http://www.w3.org/2000/svg"===a.namespaceURI&&(c.isSvgElement=!0);var d=a;for(a=a.ownerDocument;d;){const b=d.getRootNode?d.getRootNode():null;b&&b instanceof ShadowRoot?(c.isInShadowRoot=!0,c.shadowHosts.unshift(b.host),c.mixedContext.unshift({type:"shadow",host:b.host}),d=b.host):d=d.parentElement}for(d=a?.defaultView;d&&d!==window.top;)try{const b=
d.frameElement;if(b)for(c.isInIframe=!0,c.iframeChain.unshift(b),c.mixedContext.unshift({type:"iframe",frame:b}),a=b;a;){const f=a.getRootNode?a.getRootNode():null;f&&f instanceof ShadowRoot?(c.isInShadowRoot=!0,c.shadowHosts.find(k=>k===f.host)||(c.shadowHosts.unshift(f.host),c.mixedContext.unshift({type:"shadow",host:f.host})),a=f.host):a=a.parentElement}d=d.parent}catch(b){break}return c}
function buildSelectorWithContext(a,c){if(c.mixedContext&&0<c.mixedContext.length){let d="page";c.mixedContext.forEach(b=>{if("iframe"===b.type){var f=b.frame;b="iframe";f.id?b=`#${CSS.escape(f.id)}`:f.name?b=`[name="${f.name}"]`:f.title?b=`[title="${f.title}"]`:(f=f.getAttribute("src"))&&(f=f.split("/").pop().split("?")[0])&&(b=`[src*="${f}"]`);d+=`.frameLocator('${b}')`}});"page"!==d&&(c=a.replace("page.","").replace("page",""),a=d+"."+c)}else if(c.isInIframe&&0<c.iframeChain.length){let d="page";
c.iframeChain.forEach(b=>{let f="iframe";b.id?f=`#${CSS.escape(b.id)}`:b.name?f=`[name="${b.name}"]`:b.title?f=`[title="${b.title}"]`:(b=b.getAttribute("src"))&&(b=b.split("/").pop().split("?")[0])&&(f=`[src*="${b}"]`);d+=`.frameLocator('${f}')`});a=a.replace("page",d)}return a}
function countInContext(a,c){try{let d=document;if(c.mixedContext&&0<c.mixedContext.length){for(const b of c.mixedContext)try{if("iframe"===b.type){const f=b.frame;d=f.contentDocument||f.contentWindow?.document;if(!d)return 0}}catch(f){return 0}return executeCount(a,d)}if(c.isInIframe&&0<c.iframeChain.length){const b=c.iframeChain[c.iframeChain.length-1];d=b.contentDocument||b.contentWindow?.document;if(!d)return 0}return executeCount(a,d)}catch(d){return 0}}
function esc(a){return a.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(/\n/g," ").replace(/\s+/g," ").trim()}function querySelectorAllDeep(a,c=document){const d=[];try{d.push(...Array.from(c.querySelectorAll(a)))}catch(b){}try{c.querySelectorAll("*").forEach(b=>{b.shadowRoot&&d.push(...querySelectorAllDeep(a,b.shadowRoot))})}catch(b){}return d}
function executeCount(a,c){const d=a.endsWith(".first()"),b=a.endsWith(".last()"),f=a.match(/\.nth\((\d+)\)$/);let k=a,l=!1,t=!1,q=-1;d?(k=a.replace(/\.first\(\)$/,""),l=!0):b?(k=a.replace(/\.last\(\)$/,""),t=!0):f&&(q=parseInt(f[1]),k=a.replace(/\.nth\(\d+\)$/,""));if(l||t||0<=q){const e=executeCount(k,c);if(l||t)return 0<e?1:0;if(0<=q)return q<e?1:0}if(/\.locator\([^)]+\)(?:\.locator\([^)]+\))*\.getByText\(/.test(a)){const e=Array.from(a.matchAll(/locator\(['"`]([^'"`]+)['"`]\)/g)),g=a.match(/getByText\(['"`]([^'"`]+)['"`]/),
m=a.includes("exact: true");if(0<e.length&&g){const h=g[1];try{let p=Array.from((c.ownerDocument||c).querySelectorAll(e[0][1]));for(let r=1;r<e.length;r++){const u=e[r][1],w=[];p.forEach(v=>{try{const x=(v.shadowRoot||v).querySelectorAll(u);w.push(...Array.from(x))}catch(x){}});p=w}let n=0;p.forEach(r=>{r=findByText(h,m,r.shadowRoot||r);n+=r.length});return n}catch(p){return 0}}}if(/\.locator\([^)]+\)(?:\.locator\([^)]+\))*\.getByRole\(/.test(a)){const e=Array.from(a.matchAll(/locator\(['"`]([^'"`]+)['"`]\)/g)),
g=a.match(/getByRole\(['"`]([^'"`]+)['"`]/),m=a.match(/name:\s*['"`\/](.+?)['"`\/]/);if(0<e.length&&g){const h=g[1],p=m?m[1]:null;try{let n=Array.from((c.ownerDocument||c).querySelectorAll(e[0][1]));for(let u=1;u<e.length;u++){const w=e[u][1],v=[];n.forEach((x,y)=>{try{const z=(x.shadowRoot||x).querySelectorAll(w);v.push(...Array.from(z))}catch(z){}});n=v}let r=0;n.forEach((u,w)=>{u=findByRole(h,p,u.shadowRoot||u);r+=u.length});return r}catch(n){return 0}}}if(/\.locator\([^)]+\)(?:\.locator\([^)]+\))*\.getByLabel\(/.test(a)){const e=
Array.from(a.matchAll(/locator\(['"`]([^'"`]+)['"`]\)/g)),g=a.match(/getByLabel\(['"`]([^'"`]+)['"`]/),m=a.includes("exact: true");if(0<e.length&&g){const h=g[1];try{let p=Array.from((c.ownerDocument||c).querySelectorAll(e[0][1]));for(let r=1;r<e.length;r++){const u=e[r][1],w=[];p.forEach(v=>{try{const x=(v.shadowRoot||v).querySelectorAll(u);w.push(...Array.from(x))}catch(x){}});p=w}let n=0;p.forEach(r=>{r=findByLabel(h,m,r.shadowRoot||r);n+=r.length});return n}catch(p){return 0}}}if(/\.locator\([^)]+\)(?:\.locator\([^)]+\))*\.getByPlaceholder\(/.test(a)){const e=
Array.from(a.matchAll(/locator\(['"`]([^'"`]+)['"`]\)/g)),g=a.match(/getByPlaceholder\(['"`]([^'"`]+)['"`]/);if(0<e.length&&g){const m=g[1];try{let h=Array.from((c.ownerDocument||c).querySelectorAll(e[0][1]));for(let n=1;n<e.length;n++){const r=e[n][1],u=[];h.forEach(w=>{try{const v=(w.shadowRoot||w).querySelectorAll(r);u.push(...Array.from(v))}catch(v){}});h=u}let p=0;h.forEach(n=>{n=(n.shadowRoot||n).querySelectorAll(`[placeholder="${m}"]`);p+=n.length});return p}catch(h){return 0}}}if(a.match(/\.locator\([^)]+\)\.locator\(/)){const e=
Array.from(a.matchAll(/locator\(['"`]([^'"`]+)['"`]\)/g));if(2<=e.length)try{let g=c;c instanceof ShadowRoot?g=c.host.ownerDocument:c.ownerDocument&&(g=c.ownerDocument);let m=Array.from(g.querySelectorAll(e[0][1]));for(let h=1;h<e.length;h++){const p=e[h][1],n=[];m.forEach(r=>{try{const u=(r.shadowRoot||r).querySelectorAll(p);n.push(...Array.from(u))}catch(u){}});m=n}return m.length}catch(g){return 0}}if(a.includes("getByTestId")){const e=a.match(/getByTestId\(['"`]([^'"`]+)['"`]\)/);if(e)return querySelectorAllDeep(`[data-testid="${e[1]}"], [data-test-id="${e[1]}"], [data-test="${e[1]}"], [data-cy="${e[1]}"]`,
c).length}if(a.includes("getByRole")){const e=a.match(/getByRole\(['"`]([^'"`]+)['"`]/),g=a.match(/name:\s*\/([^\/]+)\/([gimsuy]*)/),m=a.match(/name:\s*['"`]([^'"`]+)['"`]/);if(e)return g?countByRoleDeepWithRegex(e[1],new RegExp(g[1],g[2]||""),c):m?countByRoleDeep(e[1],m[1],c):countByRoleDeep(e[1],null,c)}if(a.includes("getByLabel")){const e=a.match(/getByLabel\(['"`]([^'"`]+)['"`]/),g=a.includes("exact: true");if(e)return countByLabelDeep(e[1],g,c)}if(a.includes("getByPlaceholder")){const e=a.match(/getByPlaceholder\(['"`]([^'"`]+)['"`]/);
if(e)return querySelectorAllDeep(`[placeholder="${e[1]}"]`,c).length}if(a.includes("getByText")){const e=a.match(/getByText\(['"`]([^'"`]+)['"`]/),g=a.includes("exact: true");if(e)return countByTextDeep(e[1],g,c)}if(a.includes("getByAltText")){const e=a.match(/getByAltText\(['"`]([^'"`]+)['"`]/);if(e)return querySelectorAllDeep(`[alt="${e[1]}"]`,c).length}if(a.includes("getByTitle")){const e=a.match(/getByTitle\(['"`]([^'"`]+)['"`]/);if(e)return querySelectorAllDeep(`[title="${e[1]}"]`,c).length}if(a.includes(":has-text(")){const e=
a.match(/locator\(['"`](.+?):has-text\(["'](.+?)["']\)['"`]\)/);if(e){const h=e[2],p=querySelectorAllDeep(e[1],c);return Array.from(p).filter(n=>(n=n.innerText?.trim())&&n.includes(h)).length}const g=a.match(/locator\(`(.+?):has-text\("(.+?)"\)`\)/);if(g){const h=g[2],p=querySelectorAllDeep(g[1],c);return Array.from(p).filter(n=>(n=n.innerText?.trim())&&n.includes(h)).length}const m=a.match(/locator\(['"`]:has-text\(['"](.+?)['"]\)['"`]\)/);if(m){const h=m[1],p=querySelectorAllDeep("*",c);return Array.from(p).filter(n=>
(n=n.innerText?.trim())&&n.includes(h)).length}}if(a.includes(":text-is(")){const e=a.match(/locator\(['"`]:text-is\(['"](.+?)['"]\)['"`]\)/);if(e){const g=e[1],m=querySelectorAllDeep("*",c);return Array.from(m).filter(h=>!Array.from(h.childNodes).some(p=>3===p.nodeType&&p.textContent.trim())&&0<h.children.length?!1:h.innerText?.trim()===g).length}}if(a.includes(":text(")){const e=a.match(/locator\(['"`]:text\(['"](.+?)['"]\)['"`]\)/);if(e){const g=e[1],m=querySelectorAllDeep("*",c);return Array.from(m).filter(h=>
!Array.from(h.childNodes).some(p=>3===p.nodeType&&p.textContent.trim())&&0<h.children.length?!1:(h=h.innerText?.trim())&&h.includes(g)).length}}if(a.includes(":visible")){const e=a.match(/locator\(['"`]([^'"]+):visible['"`]\)/);if(e){const g=querySelectorAllDeep(e[1],c);return Array.from(g).filter(m=>{const h=window.getComputedStyle(m);return"none"!==h.display&&"hidden"!==h.visibility&&"0"!==h.opacity&&null!==m.offsetParent}).length}}if(a.includes(":hidden")){const e=a.match(/locator\(['"`]([^'"]+):hidden['"`]\)/);
if(e){const g=querySelectorAllDeep(e[1],c);return Array.from(g).filter(m=>{const h=window.getComputedStyle(m);return"none"===h.display||"hidden"===h.visibility||"0"===h.opacity||null===m.offsetParent}).length}}if(a.includes("//")||a.includes("//*")){let e=a.match(/locator`([^`]+)`/);e||=a.match(/locator\('([^']+)'\)/);e||=a.match(/locator\("([^"]+)"\)/);if(e&&e[1]&&(e[1].startsWith("//")||e[1].startsWith("//*")))try{return c.evaluate(e[1],c,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength}catch(g){return 0}}if(a.includes(".filter({ hasText:")||
a.includes(".filter({hasText:")){const e=a.match(/locator\((['"`])([^'"`]+)\1\)/),g=a.match(/hasText:\s*(['"`])([^'"`]+)\1/);if(e&&g){const m=e[2],h=g[2];try{const p=c.querySelectorAll(m);return Array.from(p).filter(n=>(n=n.textContent)&&n.includes(h)).length}catch(p){return 0}}}if(a.includes(".nth(")){const e=a.match(/locator\((['"`])([^'"`]+)\1\)/),g=a.match(/\.nth\((\d+)\)/);if(e&&g&&!a.endsWith(")")){const m=c.querySelectorAll(e[2]).length;return parseInt(g[1])<m?1:0}}if(a.includes("locator")&&
!a.includes(".filter(")){let e=null;const g=a.match(/locator`([^`]+)`/);if(g)e=g[1];else if(a.includes("locator('")){const m=a.indexOf("locator('")+9,h=a.substring(m),p=h.indexOf("')");-1!==p&&(e=h.substring(0,p))}else if(a.includes('locator("')){const m=a.indexOf('locator("')+9,h=a.substring(m),p=h.indexOf('")');-1!==p&&(e=h.substring(0,p))}if(e)try{return querySelectorAllDeep(e,c).length}catch(m){}}return 0}
function countByRoleDeep(a,c,d){return querySelectorAllDeep("*",d).filter(b=>(b.getAttribute("role")||getImplicitRole(b))!==a?!1:c?(b=getAccessibleName(b))&&b.includes(c):!0).length}
function countByLabelDeep(a,c,d){let b=0;querySelectorAllDeep("label",d).forEach(f=>{const k=f.textContent?.trim();if(c?k===a:k?.includes(a))f.htmlFor?querySelectorAllDeep(`#${f.htmlFor}`,d)[0]&&b++:f.querySelector("input, select, textarea")&&b++});querySelectorAllDeep("[aria-label]",d).forEach(f=>{f=f.getAttribute("aria-label");(c?f===a:f?.includes(a))&&b++});return b}
function countByTextDeep(a,c,d){return querySelectorAllDeep("*",d).filter(b=>{if(!Array.from(b.childNodes).some(f=>3===f.nodeType&&f.textContent.trim())&&0<b.children.length)return!1;b=b.textContent?.trim();return c?b===a:b?.includes(a)}).length}function countByRole(a,c,d){return Array.from(d.querySelectorAll("*")).filter(b=>(b.getAttribute("role")||getImplicitRole(b))!==a?!1:c?(b=getAccessibleName(b))&&b.includes(c):!0).length}
function countByLabel(a,c,d){let b=0;d.querySelectorAll("label").forEach(f=>{const k=f.textContent?.trim();if(c?k===a:k?.includes(a))f.htmlFor&&d.getElementById(f.htmlFor)?b++:f.querySelector("input, select, textarea")&&b++});d.querySelectorAll("[aria-label]").forEach(f=>{f=f.getAttribute("aria-label");(c?f===a:f?.includes(a))&&b++});return b}
function countByText(a,c,d){return Array.from(d.querySelectorAll("*")).filter(b=>{if(!Array.from(b.childNodes).some(f=>3===f.nodeType&&f.textContent.trim())&&0<b.children.length)return!1;b=b.textContent?.trim();return c?b===a:b?.includes(a)}).length}
function getImplicitRole(a){const c=a.tagName.toLowerCase(),d=a.type;return{button:"button",a:a.href?"link":null,input:"button"===d||"submit"===d?"button":"checkbox"===d?"checkbox":"radio"===d?"radio":"textbox",textarea:"textbox",select:"combobox",img:"img",h1:"heading",h2:"heading",h3:"heading",h4:"heading",h5:"heading",h6:"heading"}[c]||null}
function getAccessibleName(a){if(a.getAttribute("aria-label"))return a.getAttribute("aria-label");if(a.id){var c=document.querySelector(`label[for="${a.id}"]`);if(c)return c.textContent?.trim()}if(a.alt)return a.alt;c=a.tagName.toLowerCase();return"button a h1 h2 h3 h4 h5 h6".split(" ").includes(c)?a.textContent?.trim():a.placeholder?a.placeholder:null}
function generateXPath(a,c){c=a.tagName.toLowerCase();if(a.id)return`//*[@id="${a.id}"]`;if(a.name)return`//${c}[@name="${a.name}"]`;for(c=[];a&&a.nodeType===Node.ELEMENT_NODE;){let b=0;for(var d=a.previousSibling;d;)d.nodeType===Node.ELEMENT_NODE&&d.nodeName===a.nodeName&&b++,d=d.previousSibling;d=a.nodeName.toLowerCase();c.unshift(0<b?`${d}[${b+1}]`:d);a=a.parentNode;if("body"===d)break}return"//"+c.join("/")}
function isInTable(a){return null!==a.closest("table")||null!==a.closest('[role="table"]')||null!==a.closest('[role="grid"]')}function getTableRow(a){var c=a.closest("tr");return c||(c=a.closest('[role="row"]'))?c:(a=a.closest('.table-row, .grid-row, [class*="row"]'))&&a.parentElement&&(c=Array.from(a.parentElement.children),1<c.length&&c.every(d=>d.classList.toString().includes("row")))?a:null}
function extractCellTexts(a){const c=[];a.querySelectorAll('td, th, [role="cell"], [role="gridcell"]').forEach((d,b)=>{const f=d.textContent?.trim();f&&0<f.length&&100>f.length&&(0<d.querySelectorAll("button, input, a, svg").length&&3>f.replace(/[^a-zA-Z0-9]/g,"").length||c.push({index:b,text:f,element:d}))});return c}function getColumnIndex(a,c){c=Array.from(c.querySelectorAll('td, th, [role="cell"], [role="gridcell"]'));for(let d=0;d<c.length;d++)if(c[d].contains(a))return d;return-1}
function escapeXPathText(a){return a.includes("'")?`concat(${a.split("'").map(c=>`'${c}'`).join(', "\'", ')})`:`'${a}'`}
function generateSmartTableSelectors(a,c){const d=[];var b=extractCellTexts(c);if(0===b.length)return d;const f=a.tagName.toLowerCase(),k=getColumnIndex(a,c);var l=a.type||f;let t="";t="checkbox"===l?"input[@type='checkbox']":"radio"===l?"input[@type='radio']":"button"===f||"button"===l||"submit"===l?"button":"a"===f?"a":"input"===f?`input[@type='${l}']`:f;if(0<b.length){l=b[0];var q=escapeXPathText(esc(l.text));d.push({xpath:`//tr[td[contains(., ${q})]]//`+t,description:`${f} in row containing '${l.text}'`});
d.push({xpath:`//tr[td[normalize-space()=${q}]]//`+t,description:`${f} in row with exact text '${l.text}'`});0<=k&&d.push({xpath:`//tr[td[contains(., ${q})]]//td[${k+1}]//`+t,description:`${f} in column ${k+1} of row containing '${l.text}'`})}if(2<=b.length){l=b[0];q=b[1];const e=escapeXPathText(esc(l.text)),g=escapeXPathText(esc(q.text));d.push({xpath:`//tr[td[contains(., ${e})] and td[contains(., ${g})]]//`+t,description:`${f} in row with '${l.text}' and '${q.text}'`})}0<b.length&&0<=k&&b.forEach(e=>
{if(e.index!==k){const g=escapeXPathText(esc(e.text));d.push({xpath:`//tr[td[${e.index+1}][contains(., ${g})]]//td[${k+1}]//`+t,description:`${f} in column ${k+1} where column ${e.index+1} contains '${e.text}'`})}});if(a=a.closest('td, th, [role="cell"], [role="gridcell"]'))l=a.previousElementSibling,a=a.nextElementSibling,l&&(l=l.textContent?.trim())&&0<l.length&&100>l.length&&(q=escapeXPathText(esc(l)),d.push({xpath:`//td[contains(., ${q})]/following-sibling::td//`+t,description:`${f} in cell following '${l}'`})),
a&&(a=a.textContent?.trim())&&0<a.length&&100>a.length&&(l=escapeXPathText(esc(a)),d.push({xpath:`//td[contains(., ${l})]/preceding-sibling::td//`+t,description:`${f} in cell preceding '${a}'`}));(a=c.closest('table, [role="table"], [role="grid"]'))&&0<b.length&&(a=Array.from(a.querySelectorAll('tr, [role="row"]')).indexOf(c),0<=a&&(l=b[0],q=escapeXPathText(esc(l.text)),d.push({xpath:`//table//tr[${a+1}][td[contains(., ${q})]]//`+t,description:`${f} in row ${a+1} containing '${l.text}'`})));c=getTableHeaders(c);
0<c.length&&0<=k&&k<c.length&&0<b.length&&(c=c[k],b=b[0],c&&(a=escapeXPathText(esc(c)),l=escapeXPathText(esc(b.text)),d.push({xpath:`//tr[td[contains(., ${l})]]//td[count(//th[contains(., ${a})]/preceding-sibling::th) + 1]//`+t,description:`${f} under header '${c}' in row with '${b.text}'`})));return d}
function getTableHeaders(a){a=a.closest('table, [role="table"], [role="grid"]');if(!a)return[];const c=[],d=a.querySelector("thead tr, tr:first-child");d&&d.querySelectorAll('th, [role="columnheader"]').forEach(b=>{(b=b.textContent?.trim())&&c.push(b)});0===c.length&&(a=a.querySelector('tr, [role="row"]'))&&a.querySelectorAll('td, th, [role="cell"]').forEach(b=>{b=b.textContent?.trim();c.push(b||"")});return c}
function xpathToPlaywrightLocator(a,c){return{selector:`page.locator(\`${a}\`)`,description:c,xpath:a}}
function generateAllSelectors(a,c,d){const b=q=>{const e=countInContext(q,d);0<e&&c.push({selector:buildSelectorWithContext(q,d),count:e})},f=a.tagName.toLowerCase();var k=(a.innerText||a.textContent)?.trim();if(d.isInShadowRoot){a.id&&b(`page.locator('#${CSS.escape(a.id)}')`);if(a.className&&"string"===typeof a.className){var l=a.className.trim().split(/\s+/).filter(q=>q);if(0<l.length){var t="."+l.map(q=>CSS.escape(q)).join(".");b(`page.locator('${f}${t}')`);1===l.length&&b(`page.locator('${t}')`)}}a.name&&
(b(`page.locator('[name="${a.name}"]')`),b(`page.locator('${f}[name="${a.name}"]')`));a.type&&"input"===f&&b(`page.locator('input[type="${a.type}"]')`)}isInTable(a)&&!d.isInShadowRoot&&(l=getTableRow(a))&&generateSmartTableSelectors(a,l).forEach(q=>{try{let e=document;if(d.isInIframe&&0<d.iframeChain.length){const g=d.iframeChain[d.iframeChain.length-1];e=g.contentDocument||g.contentWindow?.document}d.isInShadowRoot&&0<d.shadowHosts.length&&(e=d.shadowHosts[d.shadowHosts.length-1].shadowRoot);if(e){const g=
e.evaluate(q.xpath,e,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;0<g&&c.push({selector:buildSelectorWithContext(`page.locator(\`${q.xpath}\`)`,d),count:g,description:q.description,type:"smart-table"})}}catch(e){}});a.hasAttribute("data-testid")&&b(`page.getByTestId('${esc(a.getAttribute("data-testid"))}')`);["data-test-id","data-test","data-cy"].forEach(q=>{a.hasAttribute(q)&&b(`page.locator('[${q}="${esc(a.getAttribute(q))}"]')`)});if(l=a.getAttribute("role")||getImplicitRole(a))(t=
getAccessibleName(a))&&100>t.length&&(b(`page.getByRole('${l}', { name: '${esc(t)}' })`),b(`page.getByRole('${l}', { name: /${t.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}/i })`)),b(`page.getByRole('${l}')`);l=null;a.id&&(t=d.rootDocument.querySelector(`label[for="${a.id}"]`))&&(l=t.textContent?.trim());l||(t=a.closest("label"))&&(l=t.textContent?.trim());!l&&a.getAttribute("aria-label")&&(l=a.getAttribute("aria-label"));l&&100>l.length&&(b(`page.getByLabel('${esc(l)}')`),b(`page.getByLabel('${esc(l)}', { exact: true })`));
a.placeholder&&100>a.placeholder.length&&(b(`page.getByPlaceholder('${esc(a.placeholder)}')`),b(`page.getByPlaceholder('${esc(a.placeholder)}', { exact: true })`));k&&0<k.length&&100>k.length&&(b(`page.getByText('${esc(k)}', { exact: true })`),b(`page.getByText('${esc(k)}')`),b(`page.locator(\'${f}:has-text("${esc(k)}")\')`),b(`page.locator(':text-is("${esc(k)}")')`),b(`page.locator(':text("${esc(k)}")')`),b(`page.locator(':has-text("${esc(k)}")')`),b(`page.locator('${f}:text-is("${esc(k)}")')`),
b(`page.locator('${f}:text("${esc(k)}")')`));a.alt&&100>a.alt.length&&(b(`page.getByAltText('${esc(a.alt)}')`),b(`page.getByAltText('${esc(a.alt)}', { exact: true })`));a.title&&100>a.title.length&&(b(`page.getByTitle('${esc(a.title)}')`),b(`page.getByTitle('${esc(a.title)}', { exact: true })`));d.isInShadowRoot||(a.id&&(b(`page.locator('#${CSS.escape(a.id)}')`),b(`page.locator('#${CSS.escape(a.id)}:visible')`)),a.name&&(b(`page.locator('[name="${a.name}"]')`),b(`page.locator('${f}[name="${a.name}"]')`)),
a.className&&"string"===typeof a.className&&(l=a.className.trim().split(/\s+/).filter(q=>q),0<l.length&&(t="."+l.map(q=>CSS.escape(q)).join("."),b(`page.locator('${f}${t}')`),b(`page.locator('${f}${t}:visible')`),1===l.length&&b(`page.locator('${t}')`))),a.type&&"input"===f&&b(`page.locator('input[type="${a.type}"]')`),b(`page.locator('${f}:visible')`));d.isSvgElement&&(a.id&&b(`page.locator('svg #${CSS.escape(a.id)}')`),a.className?.baseVal&&(l=a.className.baseVal.trim().split(/\s+/).filter(q=>q),
0<l.length&&(l="."+l.map(q=>CSS.escape(q)).join("."),b(`page.locator('svg ${f}${l}')`))),["data-icon","data-name","aria-label"].forEach(q=>{a.hasAttribute(q)&&b(`page.locator('svg [${q}="${a.getAttribute(q)}"]')`)}),k&&50>k.length&&b(`page.locator('svg ${f}:has-text("${esc(k)}")')`));k&&100>k.length&&(b(`page.locator('${f}').filter({ hasText: '${esc(k)}' })`),b(`page.locator('${f}').filter({ hasText: '${esc(k)}' }).first()`),b(`page.locator('${f}').filter({ hasText: '${esc(k)}' }).last()`));a.parentElement&&
(l=Array.from(a.parentElement.children),0<=l.indexOf(a)&&(k=a.parentElement.tagName.toLowerCase(),a.parentElement.id?k=`#${CSS.escape(a.parentElement.id)}`:a.parentElement.className&&"string"===typeof a.parentElement.className&&(t=a.parentElement.className.trim().split(/\s+/).filter(q=>q),0<t.length&&(k="."+t.map(q=>CSS.escape(q)).join("."),k=`${a.parentElement.tagName.toLowerCase()}${k}`)),l=l.filter(q=>q.tagName===a.tagName),1<l.length&&(l=l.indexOf(a),b(`page.locator('${k}').locator('${f}').nth(${l})`))))}
function analyzeElement(a){analyzeElementContext(a);a=generatePlaywrightSelectors(a);displaySelectors(a);return a}function getBest(a){return generatePlaywrightSelectors(a)[0]||null}function getUnique(a){return generatePlaywrightSelectors(a).filter(c=>1===c.count)}
function getSelectorMatches(a){try{a=convertPythonToJavaScript(a);a=convertJavaToJavaScript(a);a=normalizeLegacyOperators(a);const c=validateSelectorSyntax(a);if(!c.isValid)return"Invalid Playwright Locator: "+c.error.split("\u2022")[0];const d=parseSelectorContext(a);let b=navigateToContext(d);if(!b)return[];const f=extractCleanSelector(a);if(f.includes("frameLocator")){const k=f.split(/\.frameLocator\([^)]+\)/);return executeGetElements("page"+k[k.length-1],b)}return executeGetElements(f,b)}catch(c){return console.error("Error in getSelectorMatches:",
c),[]}}
function executeGetElements(a,c){const d=a.endsWith(".first()"),b=a.endsWith(".last()"),f=a.match(/\.nth\((\d+)\)$/);let k=a,l=!1,t=!1,q=-1;d?(k=a.replace(/\.first\(\)$/,""),l=!0):b?(k=a.replace(/\.last\(\)$/,""),t=!0):f&&(q=parseInt(f[1]),k=a.replace(/\.nth\(\d+\)$/,""));if(l||t||0<=q){const e=executeGetElements(k,c);if(l)return 0<e.length?[e[0]]:[];if(t)return 0<e.length?[e[e.length-1]]:[];if(0<=q)return q<e.length?[e[q]]:[]}if(/\.locator\([^)]+\)(?:\.locator\([^)]+\))*\.getByText\(/.test(a)){const e=Array.from(a.matchAll(/locator\(['"`]([^'"`]+)['"`]\)/g)),
g=a.match(/getByText\(['"`]([^'"`]+)['"`]/),m=a.includes("exact: true");if(0<e.length&&g){const h=g[1];try{let p=Array.from((c.ownerDocument||c).querySelectorAll(e[0][1]));for(let r=1;r<e.length;r++){const u=e[r][1],w=[];p.forEach(v=>{try{const x=(v.shadowRoot||v).querySelectorAll(u);w.push(...Array.from(x))}catch(x){}});p=w}const n=[];p.forEach(r=>{r=findByText(h,m,r.shadowRoot||r);n.push(...r)});return n}catch(p){return[]}}}if(/\.locator\([^)]+\)(?:\.locator\([^)]+\))+\.getBy/.test(a)||a.match(/\.locator\([^)]+\)\.getByRole\(/)){const e=
Array.from(a.matchAll(/locator\(['"`]([^'"`]+)['"`]\)/g)),g=a.match(/getByRole\(['"`]([^'"`]+)['"`]/),m=a.match(/name:\s*['"`\/](.+?)['"`\/]/);if(0<e.length&&g){const h=g[1],p=m?m[1]:null;try{let n=Array.from((c.ownerDocument||c).querySelectorAll(e[0][1]));for(let u=1;u<e.length;u++){const w=e[u][1],v=[];n.forEach(x=>{try{const y=(x.shadowRoot||x).querySelectorAll(w);v.push(...Array.from(y))}catch(y){}});n=v}const r=[];n.forEach(u=>{u=findByRole(h,p,u.shadowRoot||u);r.push(...u)});return r}catch(n){return[]}}}if(/\.locator\([^)]+\)(?:\.locator\([^)]+\))*\.getByLabel\(/.test(a)){const e=
Array.from(a.matchAll(/locator\(['"`]([^'"`]+)['"`]\)/g)),g=a.match(/getByLabel\(['"`]([^'"`]+)['"`]/),m=a.includes("exact: true");if(0<e.length&&g){const h=g[1];try{let p=Array.from((c.ownerDocument||c).querySelectorAll(e[0][1]));for(let r=1;r<e.length;r++){const u=e[r][1],w=[];p.forEach(v=>{try{const x=(v.shadowRoot||v).querySelectorAll(u);w.push(...Array.from(x))}catch(x){}});p=w}const n=[];p.forEach(r=>{r=findByLabel(h,m,r.shadowRoot||r);n.push(...r)});return n}catch(p){return[]}}}if(/\.locator\([^)]+\)(?:\.locator\([^)]+\))*\.getByPlaceholder\(/.test(a)){const e=
Array.from(a.matchAll(/locator\(['"`]([^'"`]+)['"`]\)/g)),g=a.match(/getByPlaceholder\(['"`]([^'"`]+)['"`]/);if(0<e.length&&g){const m=g[1];try{let h=Array.from((c.ownerDocument||c).querySelectorAll(e[0][1]));for(let n=1;n<e.length;n++){const r=e[n][1],u=[];h.forEach(w=>{try{const v=(w.shadowRoot||w).querySelectorAll(r);u.push(...Array.from(v))}catch(v){}});h=u}const p=[];h.forEach(n=>{n=(n.shadowRoot||n).querySelectorAll(`[placeholder="${m}"]`);p.push(...Array.from(n))});return p}catch(h){return[]}}}if(a.match(/\.locator\([^)]+\)\.locator\(/)){const e=
Array.from(a.matchAll(/locator\(['"`]([^'"`]+)['"`]\)/g));if(2<=e.length)try{let g=c;c instanceof ShadowRoot?g=c.host.ownerDocument:c.ownerDocument&&(g=c.ownerDocument);let m=Array.from(g.querySelectorAll(e[0][1]));for(let h=1;h<e.length;h++){const p=e[h][1],n=[];m.forEach(r=>{try{const u=(r.shadowRoot||r).querySelectorAll(p);n.push(...Array.from(u))}catch(u){}});m=n}return m}catch(g){return[]}}if(a.includes("getByTestId")){const e=a.match(/getByTestId\(['"`]([^'"`]+)['"`]\)/);if(e)return querySelectorAllDeep(`[data-testid="${e[1]}"], [data-test-id="${e[1]}"], [data-test="${e[1]}"], [data-cy="${e[1]}"]`,
c)}if(a.includes("getByRole")){const e=a.match(/getByRole\(['"`]([^'"`]+)['"`]/),g=a.match(/name:\s*\/([^\/]+)\/([gimsuy]*)/),m=a.match(/name:\s*['"`]([^'"`]+)['"`]/);if(e)return g?findByRoleDeepWithRegex(e[1],new RegExp(g[1],g[2]||""),c):m?findByRoleDeep(e[1],m[1],c):findByRoleDeep(e[1],null,c)}if(a.includes("getByLabel")){const e=a.match(/getByLabel\(['"`]([^'"`]+)['"`]/),g=a.includes("exact: true");if(e)return findByLabelDeep(e[1],g,c)}if(a.includes("getByPlaceholder")){const e=a.match(/getByPlaceholder\(['"`]([^'"`]+)['"`]/);
if(e)return querySelectorAllDeep(`[placeholder="${e[1]}"]`,c)}if(a.includes("getByText")){const e=a.match(/getByText\(['"`]([^'"`]+)['"`]/),g=a.includes("exact: true");if(e)return findByTextDeep(e[1],g,c)}if(a.includes("getByAltText")){const e=a.match(/getByAltText\(['"`]([^'"`]+)['"`]/);if(e)return querySelectorAllDeep(`[alt="${e[1]}"]`,c)}if(a.includes("getByTitle")){const e=a.match(/getByTitle\(['"`]([^'"`]+)['"`]/);if(e)return querySelectorAllDeep(`[title="${e[1]}"]`,c)}if(a.includes(":has-text(")){const e=
a.match(/locator\(['"`](.+?):has-text\(["'](.+?)["']\)['"`]\)/);if(e){const h=e[2],p=querySelectorAllDeep(e[1],c);return Array.from(p).filter(n=>(n=n.innerText?.trim())&&n.includes(h))}const g=a.match(/locator\(`(.+?):has-text\("(.+?)"\)`\)/);if(g){const h=g[2],p=querySelectorAllDeep(g[1],c);return Array.from(p).filter(n=>(n=n.innerText?.trim())&&n.includes(h))}const m=a.match(/locator\(['"`]:has-text\(['"](.+?)['"]\)['"`]\)/);if(m){const h=m[1],p=querySelectorAllDeep("*",c);return Array.from(p).filter(n=>
(n=n.innerText?.trim())&&n.includes(h))}}if(a.includes(":text-is(")){const e=a.match(/locator\(['"`]:text-is\(['"](.+?)['"]\)['"`]\)/);if(e){const g=e[1],m=querySelectorAllDeep("*",c);return Array.from(m).filter(h=>!Array.from(h.childNodes).some(p=>3===p.nodeType&&p.textContent.trim())&&0<h.children.length?!1:h.innerText?.trim()===g)}}if(a.includes(":text(")){const e=a.match(/locator\(['"`]:text\(['"](.+?)['"]\)['"`]\)/);if(e){const g=e[1],m=querySelectorAllDeep("*",c);return Array.from(m).filter(h=>
!Array.from(h.childNodes).some(p=>3===p.nodeType&&p.textContent.trim())&&0<h.children.length?!1:(h=h.innerText?.trim())&&h.includes(g))}}if(a.includes(":visible")){const e=a.match(/locator\(['"`]([^'"]+):visible['"`]\)/);if(e){const g=querySelectorAllDeep(e[1],c);return Array.from(g).filter(m=>{const h=window.getComputedStyle(m);return"none"!==h.display&&"hidden"!==h.visibility&&"0"!==h.opacity&&null!==m.offsetParent})}}if(a.includes(":hidden")){const e=a.match(/locator\(['"`]([^'"]+):hidden['"`]\)/);
if(e){const g=querySelectorAllDeep(e[1],c);return Array.from(g).filter(m=>{const h=window.getComputedStyle(m);return"none"===h.display||"hidden"===h.visibility||"0"===h.opacity||null===m.offsetParent})}}if(a.includes("//")||a.includes("//*")){let e=a.match(/locator`([^`]+)`/);e||=a.match(/locator\('([^']+)'\)/);e||=a.match(/locator\("([^"]+)"\)/);if(e&&e[1]&&(e[1].startsWith("//")||e[1].startsWith("//*")))try{const g=c.evaluate(e[1],c,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null),m=[];for(let h=
0;h<g.snapshotLength;h++)m.push(g.snapshotItem(h));return m}catch(g){return[]}}if(a.includes(".filter({ hasText:")||a.includes(".filter({hasText:")){const e=a.match(/locator\((['"`])([^'"`]+)\1\)/),g=a.match(/hasText:\s*(['"`])([^'"`]+)\1/);if(e&&g){const m=e[2],h=g[2];try{const p=c.querySelectorAll(m);return Array.from(p).filter(n=>(n=n.innerText)?n.includes(h):!1)}catch(p){return[]}}}if(a.includes(".filter({ has:")){const e=a.match(/locator\((['"`])([^'"`]+)\1\)/),g=a.match(/has:\s*page\.locator\((['"`])([^'"`]+)\1\)/);
if(e&&g){const m=e[2],h=g[2];try{const p=c.querySelectorAll(m);return Array.from(p).filter(n=>{try{return null!==n.querySelector(h)}catch(r){return!1}})}catch(p){return[]}}}if(a.includes("locator")&&!a.includes(".filter(")){let e=null;const g=a.match(/locator`([^`]+)`/);if(g)e=g[1];else if(a.includes("locator('")){const m=a.indexOf("locator('")+9,h=a.substring(m),p=h.indexOf("')");-1!==p&&(e=h.substring(0,p))}else if(a.includes('locator("')){const m=a.indexOf('locator("')+9,h=a.substring(m),p=h.indexOf('")');
-1!==p&&(e=h.substring(0,p))}if(e)try{if(!e.startsWith("//")&&!e.startsWith("//*"))return querySelectorAllDeep(e,c)}catch(m){return[]}}if(a.includes(".nth(")){const e=a.match(/locator\((['"`])([^'"`]+)\1\)/),g=a.match(/\.nth\((\d+)\)/);if(e&&g&&!a.endsWith(")")){const m=Array.from(c.querySelectorAll(e[2])),h=parseInt(g[1]);return h<m.length?[m[h]]:[]}}if(a.includes("locator")){const e=a.match(/locator\((['"`])([^'"`]+)\1\)/)||a.match(/locator\(`([^`]+)`\)/);if(e)try{return querySelectorAllDeep(e[2]||
e[1],c)}catch(g){}}return[]}function findByRoleDeep(a,c,d){return querySelectorAllDeep("*",d).filter(b=>(b.getAttribute("role")||getImplicitRole(b))!==a?!1:c?(b=getAccessibleName(b))&&b.includes(c):!0)}
function findByLabelDeep(a,c,d){const b=[];querySelectorAllDeep("label",d).forEach(f=>{const k=f.textContent?.trim();if(c?k===a:k?.includes(a))f.htmlFor?(f=querySelectorAllDeep(`#${f.htmlFor}`,d)[0])&&b.push(f):(f=f.querySelector("input, select, textarea"))&&b.push(f)});querySelectorAllDeep("[aria-label]",d).forEach(f=>{const k=f.getAttribute("aria-label");(c?k===a:k?.includes(a))&&!b.includes(f)&&b.push(f)});return b}
function findByTextDeep(a,c,d){return querySelectorAllDeep("*",d).filter(b=>{if(!Array.from(b.childNodes).some(f=>3===f.nodeType&&f.textContent.trim())&&0<b.children.length)return!1;b=b.textContent?.trim();return c?b===a:b?.includes(a)})}function findByRole(a,c,d){return Array.from(d.querySelectorAll("*")).filter(b=>(b.getAttribute("role")||getImplicitRole(b))!==a?!1:c?(b=getAccessibleName(b))&&b.includes(c):!0)}
function findByLabel(a,c,d){const b=[];d.querySelectorAll("label").forEach(f=>{const k=f.textContent?.trim();if(c?k===a:k?.includes(a))f.htmlFor?(f=d.getElementById(f.htmlFor))&&b.push(f):(f=f.querySelector("input, select, textarea"))&&b.push(f)});d.querySelectorAll("[aria-label]").forEach(f=>{const k=f.getAttribute("aria-label");(c?k===a:k?.includes(a))&&!b.includes(f)&&b.push(f)});return b}
function findByText(a,c,d){return Array.from(d.querySelectorAll("*")).filter(b=>{if(!Array.from(b.childNodes).some(f=>3===f.nodeType&&f.textContent.trim())&&0<b.children.length)return!1;b=b.textContent?.trim();return c?b===a:b?.includes(a)})}
function testSelector(a){a=getSelectorMatches(a);0<a.length&&a.slice(0,5).forEach((c,d)=>{c.tagName.toLowerCase();c.className&&"string"===typeof c.className&&c.className.split(" ").filter(b=>b).slice(0,2).join(".");c.textContent?.trim().substring(0,30)});return a}
function inspectMatches(a){a=getSelectorMatches(a);if(0===a.length)return a;a.forEach((c,d)=>{c.textContent?.trim();d="data-testid data-test aria-label placeholder alt title href".split(" ").filter(b=>c.hasAttribute(b));0<d.length&&d.forEach(b=>{})});return a}function displaySelectors(a){}
function demoLegacyConversion(){["page.locator(\"div[class='userform'] >> text=Company\")",'page.locator("table >> tr >> button")',"page.locator(\".container >> [data-testid='submit']\")"].forEach(a=>{normalizeLegacyOperators(a)})}
function listAllShadowElements(a=document.body){function c(b,f=[]){const k={tag:b.tagName?.toLowerCase(),id:b.id||null,classes:b.className&&"string"===typeof b.className?b.className.split(" ").filter(l=>l):[],path:f.join(" > "),hasShadow:!!b.shadowRoot};d.push(k);b.shadowRoot&&b.shadowRoot.querySelectorAll("*").forEach(l=>{c(l,[...f,`${k.tag}${k.id?"#"+k.id:""}`,"(shadow)"])})}const d=[];a.querySelectorAll("*").forEach(b=>c(b,[]));return d}
function convertPythonToJavaScript(a){if(!a.includes("_")&&!a.includes("name=")&&!a.includes("re.compile"))return a;let c=a;Object.entries({get_by_role:"getByRole",get_by_text:"getByText",get_by_label:"getByLabel",get_by_placeholder:"getByPlaceholder",get_by_alt_text:"getByAltText",get_by_title:"getByTitle",get_by_test_id:"getByTestId",frame_locator:"frameLocator"}).forEach(([d,b])=>{c=c.replace(new RegExp(`\\.${d}\\(`,"g"),`.${b}(`)});c=c.replace(/re\.compile\(r["']([^"']+)["'](?:,\s*re\.(\w+))?\)/g,
(d,b,f)=>{d="";f&&(d={IGNORECASE:"i",MULTILINE:"m",DOTALL:"s",I:"i",M:"m",S:"s"}[f]||"");return`/${b}/${d}`});c=c.replace(/re\.compile\(r["']([^"']+)["'],\s*([^)]+)\)/g,(d,b,f)=>{d="";if(f.includes("IGNORECASE")||f.includes("re.I"))d+="i";if(f.includes("MULTILINE")||f.includes("re.M"))d+="m";if(f.includes("DOTALL")||f.includes("re.S"))d+="s";return`/${b}/${d}`});c=c.replace(/(getByRole|getByText|getByLabel|getByPlaceholder)\(["']([^"']+)["'],\s*name=\/([^\/]+)\/([gimsuy]*)\)/g,(d,b,f,k,l)=>`${b}('${f.replace(/'/g,
"\\'")}', { name: /${k}/${l} })`);c=c.replace(/(getByRole|getByText|getByLabel|getByPlaceholder)\(["']([^"']+)["'],\s*name=["']([^"']+)["']\)/g,(d,b,f,k)=>`${b}('${f.replace(/'/g,"\\'")}', { name: '${k.replace(/'/g,"\\'")}' })`);c=c.replace(/(getByText|getByLabel|getByPlaceholder)\(["']([^"']+)["'],\s*exact=True\)/g,(d,b,f)=>`${b}('${f.replace(/'/g,"\\'")}', { exact: true })`);c=c.replace(/(getByText|getByLabel|getByPlaceholder)\(["']([^"']+)["'],\s*exact=False\)/g,(d,b,f)=>`${b}('${f.replace(/'/g,
"\\'")}', { exact: false })`);c=c.replace(/\.filter\(\s*has_text=["']([^"']+)["']\s*\)/g,(d,b)=>`.filter({ hasText: '${b.replace(/'/g,"\\'")}' })`);c=c.replace(/\.filter\(\s*has=([^)]+)\)/g,(d,b)=>`.filter({ has: ${b} })`);c=c.replace(/\.nth\((\d+)\)/g,".nth($1)");c=c.replace(/\.first\(\)/g,".first()");c=c.replace(/\.last\(\)/g,".last()");return c.trim()}
function findByRoleDeepWithRegex(a,c,d){return querySelectorAllDeep("*",d).filter(b=>(b.getAttribute("role")||getImplicitRole(b))!==a?!1:c?(b=getAccessibleName(b))&&c.test(b):!0)}function countByRoleDeepWithRegex(a,c,d){return querySelectorAllDeep("*",d).filter(b=>(b.getAttribute("role")||getImplicitRole(b))!==a?!1:c?(b=getAccessibleName(b))&&c.test(b):!0).length};
