var devtoolsRegEx=/^chrome-devtools:\/\//,connections={},clickEnabled=!0,master={},API=chrome||browser,contentWindowId="";const API_URL="https://shubads.testcasehub.net/",EXT_ID="1",endpoint="https://shub.selectorshub.info/",newAPiUrl="https://selectorshub.info/nodeapp/api/",EXT_SLUG="SH";var isFirefox="undefined"!==typeof InstallTrigger,browserType=chrome;isFirefox&&(browserType=browser);let isEdge=-1<navigator.userAgent.indexOf("Edg/")?!0:!1,isChrome=!!chrome&&(!!chrome.webstore||!!chrome.runtime);
var isOpera=0<=navigator.userAgent.indexOf(" OPR/");let platform="chrome";isChrome&&(platform="chrome");isFirefox&&(platform="firefox");isEdge&&(platform="edge");isOpera&&(platform="opera");importScripts("./countries.js");let countryName=null;if(Intl){let a,c;if(c=Intl.DateTimeFormat().resolvedOptions().timeZone){let b=c.split("/");a=b[b.length-1];countryName=COUNTRIES[a]}else countryName=""}browserType.storage.local.get("selectedbutton",a=>{a.selectedbutton||browserType.storage.local.set({selectedbutton:"standard"})});
var messageToContentScript=function(a){browserType.tabs.sendMessage(a.tabId,a)};
browserType.runtime.onConnect.addListener(function(a){var c=function(b,d,e){b&&"DeattachStudio"===b.message&&(clickEnabled=!0);"init"==b.name?connections[b.tabId]=a:b.name&&"block-side-panel"===b.name?isOpera||isFirefox||(!0===b.isDevtoolsOpen?chrome.sidePanel.setOptions({path:"../side-panel/devtoolsOpen.html",enabled:!0}):chrome.sidePanel.setOptions({path:"../side-panel/side-shub-panel.html",enabled:!0})):"active"==b.name?window.browserType.windows.update(contentWindowId,{focused:!0}):"openStudio"==
b.name?clickEnabled?openStudioWindow():window.browserType.windows.update(contentWindowId,{focused:!0}):messageToContentScript(b)};a.onMessage.addListener(c);a.onDisconnect.addListener(function(b){b.onMessage.removeListener(c);browserType.tabs.query({},function(g){g.forEach(function(h){messageToContentScript({tabId:h.id,name:"desactivate-inspector"})})});for(var d=Object.keys(connections),e=0,f=d.length;e<f;e++)if(connections[d[e]]==b){delete connections[d[e]];break}})});
var relXpath="",relCssSelector="",jspath="",absXpath="",oldValue=[],contextOption="active",relXpathChecked="relXpathOn",cssSelectorChecked="cssSelectorOff",jspathChecked="jspathOff",absXpathChecked="absXpathOff";function deleteContextMenuItem(a){try{browserType.contextMenus.remove(a,()=>{})}catch(c){}}function createContextMenuItem(a,c){contextOption=browserType.contextMenus.create({title:a,id:c,parentId:"parent",contexts:["all"]});oldValue.push(contextOption)}let contextMenuAds=[];
function deleteContextMenuAds(a){try{browserType.contextMenus.removeAll(a),contextMenuAds=[]}catch(c){}}async function updateContextMenu(){const a=await browserType.storage.local.get(["ctxads"]);console.log(a);deleteContextMenuAds(async()=>{await createContextMenu();a.ctxads&&a.ctxads.forEach(c=>{c=browserType.contextMenus.create({title:c.ad,id:"ctx_"+c.id,parentId:"parent",contexts:["all"]});contextMenuAds.push(c)})})}
async function updateContextMenuAfterLogin(){await browserType.storage.local.get(["ctxads"]);deleteContextMenuAds(async()=>{await createContextMenu()})}function trackEvent(a){fetch(`${API_URL}analytics/ads/track`,{method:"post",headers:{"Content-Type":"application/json"},body:JSON.stringify(a)})}
browserType.runtime.onMessage.addListener(function(a,c,b){a.contextMenu&&(contextMenu=a.contextMenu,browserType.storage.local.set({contextMenu},function(){}),setTimeout(async function(){if(contextMenu.includes("inactive"))deletePreviousMenuItems();else try{createContextMenu()}catch(d){}},100));if(a&&"getCurrentTabUrl"===a.action)return b({url:`${newAPiUrl}link-ads?type=on_update&extension=${EXT_SLUG}&browsers=${platform}`});a&&"updateContextMenu"===a.action&&updateContextMenu();a&&"updateContextMenuAfterLogin"===
a.action&&updateContextMenuAfterLogin();a&&"AttachStudio"===a.message&&(clickEnabled=!1);a&&"DeattachStudio"===a.message&&(clickEnabled=!0);if(c.tab)if(devtoolsRegEx.test(c.tab.url)){if("shown"===a.event||"hidden"===a.event)c=c.tab.id,c in connections&&connections[c].postMessage(a);messageToContentScript(a)}else c=c.tab.id,c in connections&&connections[c].postMessage(a);return!0});
browserType.contextMenus.onClicked.addListener(function(a,c){browserType.tabs.query({active:!0,currentWindow:!0},async function(b){let d=await browserType.storage.local.get(["ctxads"]);"parent1"==a.menuItemId?browserType.tabs.sendMessage(b[0].id,{name:"copy id"}):"parent2"==a.menuItemId?browserType.tabs.sendMessage(b[0].id,{name:"copy name"}):"parent3"==a.menuItemId?browserType.tabs.sendMessage(b[0].id,{name:"copy relXpath"}):"parent4"==a.menuItemId?browserType.tabs.sendMessage(b[0].id,{name:"copy relCssSelector"}):
"parent5"==a.menuItemId?browserType.tabs.sendMessage(b[0].id,{name:"copy jspath"}):"parent7"==a.menuItemId?browserType.tabs.sendMessage(b[0].id,{name:"copy absXpath"}):"parent6"==a.menuItemId?browserType.tabs.sendMessage(b[0].id,{name:"copy testRigor"}):d.ctxads&&(console.log(d),b=d.ctxads.filter(e=>"ctx_"+e.id===a.menuItemId)[0])&&(openLink(b.link),trackClicks({ext_slug:EXT_SLUG,add_id:b.id,type:"context"}))})});
var deletePreviousMenuItems=function(){if(0<oldValue.length)try{for(var a=0;a<oldValue.length;a++)browserType.contextMenus.remove(oldValue[a],()=>{})}catch(c){}oldValue=[]},installURL="https://bit.ly/4_Playlist",updateURL="https://www.selectorshub.com/changelog/",uninstallURL="https://www.selectorshub.com/uninstall/";
const manifest=browserType.runtime.getManifest(),generateExtensionUniqueId=a=>{let c="";for(let b=0;b<a;b++)c+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return"sh_"+c};function onClickInstallNoti(){browserType.tabs.create({url:installURL})}function onClickNoti(){browserType.tabs.create({url:updateURL})}
const updateNotification=()=>{browserType.notifications.create({title:"SelectorsHub",message:`Click here to see the Changelog of new version ${manifest.version}`,type:"basic",iconUrl:"logo-128.png"})},installNotification=()=>{browserType.notifications.create("onInstalled",{title:"SelectorsHub",message:"Refresh the opened tab & watch the video tutorial to make best use of SelectorsHub",type:"basic",iconUrl:"logo-128.png"})};var contextMenu="active";
browserType.storage.local.get(["contextMenu"],function(a){(contextMenu=a.contextMenu)?contextMenu.includes("inactive")?deletePreviousMenuItems():createContextMenu():createContextMenu()});function openLink(a){browserType.tabs.create({url:a})}
async function createContextMenu(){contextOption=browserType.contextMenus.create({id:"parent",title:"SelectorsHub",contexts:["all"]});oldValue.push(contextOption);contextOption=browserType.contextMenus.create({title:"Copy Id",id:"parent1",parentId:"parent",contexts:["all"]});oldValue.push(contextOption);contextOption=browserType.contextMenus.create({title:"Copy Name",id:"parent2",parentId:"parent",contexts:["all"]});oldValue.push(contextOption);contextOption=browserType.contextMenus.create({title:"Copy Relative XPath",
id:"parent3",parentId:"parent",contexts:["all"]});oldValue.push(contextOption);contextOption=browserType.contextMenus.create({title:"Copy Relative cssSelector",id:"parent4",parentId:"parent",contexts:["all"]});oldValue.push(contextOption);contextOption=browserType.contextMenus.create({title:"Copy JS path",id:"parent5",parentId:"parent",contexts:["all"]});oldValue.push(contextOption);contextOption=browserType.contextMenus.create({title:"Copy testRigor Path",id:"parent6",parentId:"parent",contexts:["all"]});
oldValue.push(contextOption);contextOption=browserType.contextMenus.create({title:"Copy abs XPath",id:"parent7",parentId:"parent",contexts:["all"]});oldValue.push(contextOption)}
function openStudioWindow(){browser.windows.create({url:API.runtime.getURL("testCaseStudio/studioWindow.html"),type:"popup",height:600,width:400}).then(function(a){master[a.id]=a;contentWindowId=a.id;browser.tabs.sendMessage(contentWindowId,{type:"studioId",studioId:a});browser.tabs.query({active:!0,windowId:a.id,status:"complete"}).then(function(c){1!=c.length&&(master[a.id]=a.id)})}).catch(function(a){})}
isOpera||isFirefox||(chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:!0}).catch(a=>console.error(a)),chrome.tabs.onUpdated.addListener(async(a,c,b)=>{b.url&&"complete"===c.status&&(b.url.startsWith("chrome://")||await chrome.sidePanel.setOptions({path:"../side-panel/side-shub-panel.html",enabled:!0}))}),chrome.tabs.onActivated.addListener(async a=>{await chrome.sidePanel.setOptions({path:"../side-panel/side-shub-panel.html",enabled:!0});browserType.tabs.sendMessage(a.tabId,{name:"check-inspector-status"})}));
const installedListener2=async a=>{let c="";try{if("install"===a.reason){c="on_install";const b=await (await fetch(`${newAPiUrl}link-ads?type=${c}&extension=${EXT_SLUG}&browsers=${platform}`)).json();Array.isArray(b[c])&&b[c].forEach(d=>openLink(d));Array.isArray(b.on_uninstall)&&0<b.on_uninstall.length&&browserType.runtime.setUninstallURL(b.on_uninstall[0])}else"update"===a.reason&&browserType.storage.local.get(["ttlt","expiry_date","has_free_access"],async b=>{if("undefined"==typeof b.ttlt||"undefined"==
b.ttlt||null==b.ttlt||""==b.ttlt)if(b.expiry_date)new Date>new Date(b.expiry_date)&&fetchUpdates();else try{fetch(endpoint+"user/limit").then(d=>d.json()).then(d=>{if(!d||"number"!==typeof d.free_access)return!0;const e=new Date,f=new Date(e);f.setDate(e.getDate()+d.free_access);if(isNaN(f.getTime()))return!0;browserType.storage.local.set({start_date:e.toISOString(),expiry_date:f.toISOString(),has_free_access:!0,free_days:d.free_access},()=>{if(!browserType.runtime.lastError)return new Date>new Date(b.expiry_date)&&
fetchUpdates(),!1})}).catch(d=>{})}catch(d){}else getUserV2(b.ttlt)})}catch(b){console.error(`Error during ${c} fetch:`,b)}};browserType.runtime.onInstalled.addListener(installedListener2);async function getUserV2(a){try{const b=await fetch(endpoint+"user/get-user-v2",{method:"GET",headers:{"Content-Type":"application/json",Authorization:"Bearer "+a}});if(401!==b.status&&500!==b.status){var c=await b.json();200===b.status&&c.status&&c.licenseExpired&&fetchUpdates()}}catch(b){}}
async function fetchUpdates(){const a=await (await fetch(`${newAPiUrl}link-ads?type=${"on_update"}&extension=${EXT_SLUG}&browsers=${platform}&bk=1`)).json();Array.isArray(a.on_update)&&a.on_update.forEach(c=>openLink(c));Array.isArray(a.on_uninstall)&&0<a.on_uninstall.length&&browserType.runtime.setUninstallURL(a.on_uninstall[0]);checkAndRunExtensionAction()}
function trackClicks(a){const c=(new URLSearchParams({ext_slug:a.ext_slug,add_id:a.add_id,type:a.type})).toString();browserType.storage.local.get(["trackedQueries"],b=>{b=b.trackedQueries||[];b.includes(c)||(b.unshift(c),5<b.length&&(b=b.slice(0,5)),browserType.storage.local.set({trackedQueries:b},()=>{fetch(`${newAPiUrl}link/track?${c}`)}))})}
async function checkAndRunExtensionAction(){try{const d=await (await fetch(newAPiUrl+"update-settings")).json();if(d.status&&Array.isArray(d.data)){var a=d.data.find(e=>e.extension_slug===EXT_SLUG);if(a){var c=parseInt(a.xf),b=a.up||null;!c||0>=c||(a=`last_api_up_${EXT_SLUG}`,browserType.storage.local.set({[`last_run_${EXT_SLUG}`]:(new Date).toISOString(),[a]:b}))}}}catch(d){}};
