var endpoint="https://shub.selectorshub.info/";let resendTimer;var isLoggedIn=!1;function startCountdown(){let c=60;const a=$("#resend_btn");a.prop("disabled",!0).css("opacity","0.6");a.val(`Resend in ${c}s`);resendTimer=setInterval(function(){c--;a.val(`Resend in ${c}s`);0>=c&&(clearInterval(resendTimer),a.prop("disabled",!1).css("opacity","1"),a.val("Resend verification code"))},1E3)}
function checkSessionId(){chrome.storage.local.get(["ttlt","expiry_date","has_free_access"],c=>{if("undefined"==typeof c.ttlt||"undefined"==c.ttlt||null==c.ttlt||""==c.ttlt)if(allow=isLoggedIn=!1,c.expiry_date)new Date>new Date(c.expiry_date)?(allow=!1,chrome.storage.local.set({has_free_access:!1})):allow=!0,showPt(allow),allow||setTimeout(()=>{openLoginForm()},3E3);else try{$(".sidebar-body .sponsor").hide(),fetch(endpoint+"user/limit").then(a=>a.json()).then(a=>{if(!a||"number"!==typeof a.free_access)throw Error("Invalid response: free_days missing or not a number");
const b=new Date,d=new Date(b);d.setDate(b.getDate()+a.free_access);if(isNaN(d.getTime()))throw Error("Expiry date calculation failed");chrome.storage.local.set({start_date:b.toISOString(),expiry_date:d.toISOString(),has_free_access:!0,free_days:a.free_access},()=>{if(!chrome.runtime.lastError)return new Date>new Date(c.expiry_date)?(allow=!1,chrome.storage.local.set({has_free_access:!1})):allow=!0,showPt(allow),allow||setTimeout(()=>{openLoginForm()},3E3),!1})}).catch(a=>{})}catch(a){}else isLoggedIn=
!0,$(".sidebar-body .sponsor, .patronRequest").hide(),checkUser(c.ttlt)})}
function showPt(c){checkForUpdates(c);isLoggedIn?($(".patronRequest").css("display","flex"),$(".patronRequest .after-login").show(),$(".upgradeBtn.top.home-login-btn").hide(),$(".patronRequest .after-login").show(),$(".patronRequest").children(":not(.after-login)").hide()):($(".popup__actions__container").addClass("update-upgrade-panel"),$(".patronRequest .after-login").hide(),$(".patronRequest").children(":not(.after-login)").show(),$(".upgradeBtn.home-login-btn").show());c?(browserType.storage.local.remove("newUpdate"),
$(".popup__actions__container").addClass("update-upgrade-panel"),$(".upgradeBtn.top.after-login-top-upgrade").hide(),window.location.pathname.includes("/side-panel/side-shub-panel.html")&&$("#selectorsHubEleContainer").css("max-height","calc(100% - 320px)"),$(".requestHeader.sponsor").hide(),$(".ads__text, .ads__container, .ads__viewer, .image__ad, .top_ads__viewer, #image-ads").hide()):($(".upgradeBtn.top.home-login-btn").show(),$(".popup__actions__container").removeClass("update-upgrade-panel"),
window.location.pathname.includes("/side-panel/side-shub-panel.html")&&$("#selectorsHubEleContainer").css("max-height","60px"),fetchProductUpdates(),$(".requestHeader.sponsor").show(),$(".ads__text, .ads__container, .ads__viewer,  #image-ads").show(),$(".image__ad").css("display","flex"));$(".upgradeBtn.top.upgrade-lifetime").hide();!isLoggedIn&&c?($(".upgradeBtn.top.home-login-btn").hide(),$(".upgradeBtn.home-login-btn").show(),$(".upgradeBtn.home-login-btn").html('<span class="upgrade toolTip">Login</span>Login'),
$(".update-product").hide(),$(".under-free-limit").show(),window.location.pathname.includes("/side-panel/side-shub-panel.html")&&$(".expired-case, .extra-sep").hide()):isLoggedIn||c?isLoggedIn&&!c?window.location.pathname.includes("/side-panel/side-shub-panel.html")?($(".upgradeBtn.top.upgrade-lifetime").show(),$(".upgradeBtn.home-login-btn").html('<span class="upgrade toolTip">Upgrade to pro</span>Upgrade to Pro'),$(".home-login-btn.under-popup").addClass("profile").removeClass("home-login-btn").html('<span class="upgrade toolTip">Go Ads Free</span>Go Ads Free'),
$(".update-product").show(),$(".profile-re").hide(),$(".under-free-limit").show(),$(".after-login.upgradeBtn, .next-version").hide()):($(".upgradeBtn.top.upgrade-lifetime").show(),$(".home-login-btn.under-popup").addClass("profile").removeClass("home-login-btn").html('<span class="upgrade toolTip">Go Ads Free</span>Go Ads Free'),$(".under-free-limit").hide(),$(".update-product").show(),$(".profile-re").hide(),$(".after-login.upgradeBtn").hide(),$(".hide-when-request").addClass("profile").removeClass("home-login-btn").html('<span class="upgrade toolTip">Go Ads Free</span>Go Ads Free').show()):
isLoggedIn&&c&&$(".upgradeBtn.top.upgrade-lifetime").hide():($(".upgradeBtn.top.home-login-btn").hide(),$(".upgradeBtn.home-login-btn").html('<span class="upgrade toolTip">Go Ads Free</span>Go Ads Free'))}function checkForUpdates(c){c||checkAndRunExtensionAction()}
$(document).ready(function(){$(".back-btn").show();$(document).on("click",".back-btn",function(){const c=$(this).attr("data-next");"login"===c?($(".container").slideDown(250),$("#register_form").slideUp(250),$(".back-btn").attr("data-next","home")):"register"===c&&($(".register-container").hide(),$("#login-container").show(),$(".back-btn").attr("data-next","login"))});$(document).on("click",".close-all",function(){$(".back-btn").show();$(".container").slideDown(250);$("#register_form").slideUp(250);
$(".register-container").hide();$("#login-container").show();$(".back-btn").attr("data-next","login")});$(".subscription_plan").on("click",function(){window.open("https://selectorshub.com/how-to-get-selectorshub-ads-blocker-key/","_blank")});$("#registration_help").on("click",function(){window.open("https://selectorshub.com/how-to-get-selectorshub-ads-blocker-key/","_blank")});$("#registration_tutorial").on("click",function(){window.open("https://www.youtube.com/watch?v=qCEYfTHQ-bU","_blank")});$("#upgrade_to_pro_btn").on("click",
function(){window.open("https://selectorshub.com/selectorshub-pro/plans/","_blank")});$("#show_reg_form").on("click",()=>{$(".register-container").show();$("#login-container").hide();$(".back-btn").attr("data-next","register");showRegForm()});$(document).on("click",".home-login-btn",function(){$(".back-btn").attr("data-next","login")});$(document).on("click","#forgot_pass",function(){"register"===$(".back-btn").attr("data-next")&&$(".back-btn").click();$(".email-container, .forgetbtn, #open_login").show();
$(".licence-container, #submit_btn, #forgot_pass").hide()});$("#email-f").on("keyup",function(c){"Enter"!==c.key&&13!==c.keyCode||$(".forgetbtn").click()});$("#password").on("keyup",function(c){"Enter"!==c.key&&13!==c.keyCode||$("#submit_btn").click()});$(".open-forgot-password").click(function(){$(".forgetbtn").show();$("#submit_btn").hide();$(".password-container").hide();$(".open-forgot-password").hide();$(".open-login").show()});$(".open-login").click(function(){$(".forgetbtn").hide();$("#submit_btn").show();
$(".open-forgot-password").show();$(".open-login").hide();$(".password-container").show()});$(".forgetbtn").click(function(){let c=document.getElementById("email").value.trim();if(""==c)return $("#email").focus(),!1;loading(!0);$(".forgetbtn").prop("disabled",!0);$(".forgetbtn").val("Please wait");$.ajax({method:"POST",url:endpoint+"user/sendforgot",beforeSend:function(a){a.setRequestHeader("Content-type","application/json")},data:JSON.stringify({email:c}),success:function(a,b,d){loading(!1);$(".forgetbtn").prop("disabled",
!1);$(".forgetbtn").val("Submit");200==d.status&&a.status?$(".user-status").text(a.message).css("color","green").slideDown():(chrome.storage.local.remove("ttlt"),$(".user-status").text(a.message).css("color","red").slideDown());setTimeout(()=>{$(".user-status").slideUp()},5E3)},error:function(a,b,d){},statusCode:{500:function(a){},401:function(a){}}})});$("#submit_btn").click(function(){let c=document.getElementById("licence").value.trim();if(""==c)return $("#licence").focus(),!1;loading(!0);$("#submit_btn").prop("disabled",
!0);$("#submit_btn").val("Please wait");$.ajax({method:"POST",url:endpoint+"user/login",beforeSend:function(a){a.setRequestHeader("Content-type","application/json")},data:JSON.stringify({lk:c}),success:function(a,b,d){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");200==d.status&&a.status?(chrome.storage.local.set({ttlt:a.token}),ttlt=a.token,chrome.storage.local.set({data:a.data,messages:a.messages},function(){chrome.runtime.sendMessage({message:"loggedin"},function(e){})}),
loginIssue()):($("#submit_btn").prop("disabled",!1),$("#submit_btn").val("Login"),chrome.storage.local.remove("ttlt"),$(".subscription-status").text(a.message).slideDown(),setTimeout(()=>{$(".subscription-status").slideUp()},5E3),-1<a.message.indexOf("Already")&&$("#three-modal").show())},error:function(a,b,d){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");$(".invalid-error.invalid-credentails").text("Invalid credentials").slideDown();setTimeout(function(){document.getElementsByClassName("invalid-credentails")[0].style.display=
"none"},3E3)},statusCode:{500:function(a){},401:function(a){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");$(".invalid-error.invalid-credentails").text("Invalid credentials").slideDown();setTimeout(function(){document.getElementsByClassName("invalid-credentails").style.display="none"},3E3)}}})});$("#re_submit_btn").click(function(){let c=document.getElementById("re_licence").value.trim();if(""==c)return $("#re_licence").focus(),!1;loading(!0);$("#re_submit_btn").prop("disabled",
!0);$("#re_submit_btn").val("Please wait");$.ajax({method:"POST",url:endpoint+"user/login",beforeSend:function(a){a.setRequestHeader("Content-type","application/json")},data:JSON.stringify({lk:c}),success:function(a,b,d){loading(!1);$("#re_submit_btn").prop("disabled",!1);$("#re_submit_btn").val("Login");200==d.status&&a.status?(chrome.storage.local.set({ttlt:a.token}),ttlt=a.token,chrome.storage.local.set({data:a.data,messages:a.messages},function(){chrome.runtime.sendMessage({message:"loggedin"},
function(e){})}),loginIssue()):($("#re_submit_btn").prop("disabled",!1),$("#re_submit_btn").val("Login"),chrome.storage.local.remove("ttlt"),$(".subscription-status").text(a.message).slideDown(),setTimeout(()=>{$(".subscription-status").slideUp()},5E3),-1<a.message.indexOf("Already")&&$("#three-modal").show())},error:function(a,b,d){loading(!1);$("#re_submit_btn").prop("disabled",!1);$("#re_submit_btn").val("Login");$(".invalid-error.invalid-credentails").text("Invalid credentials").slideDown();setTimeout(function(){document.getElementsByClassName("invalid-credentails")[0].style.display=
"none"},3E3)},statusCode:{500:function(a){},401:function(a){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");$(".invalid-error.invalid-credentails").text("Invalid credentials").slideDown();setTimeout(function(){document.getElementsByClassName("invalid-credentails").style.display="none"},3E3)}}})});$("#resend_btn").click(function(){let c=document.getElementById("re-email").value.trim(),a=document.getElementById("re-full-name").value.trim();loading(!0);$(".re-actions").prop("disabled",
!0);$("#resend_btn").val("Please wait");startCountdown();$.ajax({method:"POST",url:endpoint+"user/resend-code",beforeSend:function(b){b.setRequestHeader("Content-type","application/json");b.setRequestHeader("D","shub")},data:JSON.stringify({email:c,name:a}),success:function(b,d,e){loading(!1);$(".re-actions").prop("disabled",!1);$("#resend_btn").val("Resend verification code");200==e.status&&b.status?showServerMessage(b.message,"success"):showServerMessage(b.message,"error")},error:function(b,d,e){loading(!1)},
statusCode:{500:function(b){},401:function(b){}}})});$("#verify_btn").click(function(){let c=document.getElementById("re-email").value.trim(),a=document.getElementById("re-full-name").value.trim(),b=document.getElementById("otp-code").value.trim();if(""==b)return $("#otp-code").focus(),!1;loading(!0);$(".re-actions").prop("disabled",!0);$("#verify_btn").val("Please wait");$.ajax({method:"POST",url:endpoint+"user/verify-code",beforeSend:function(d){d.setRequestHeader("Content-type","application/json");
d.setRequestHeader("D","shub")},data:JSON.stringify({email:c,name:a,otp:b}),success:function(d,e,f){loading(!1);$(".re-actions").prop("disabled",!1);$("#verify_btn").val("Submit");200==f.status&&d.status?(showServerMessage(d.message,"success"),$("#verify_btn, #resend_btn, .re-otp-container").hide(),$(".re-licence-input-container, #re_submit_btn").show(),$(".back-btn, .close-all").show()):showServerMessage(d.message,"error")},error:function(d,e,f){loading(!1)},statusCode:{500:function(d){},401:function(d){}}})});
$("#register_btn").click(function(){let c=document.getElementById("re-email").value.trim(),a=document.getElementById("re-full-name").value.trim();if(""===a)return $("#re-full-name").focus(),!1;if(""==c)return $("#re-email").focus(),!1;loading(!0);$(".re-actions").prop("disabled",!0);$.ajax({method:"POST",url:endpoint+"user/register",beforeSend:function(b){b.setRequestHeader("Content-type","application/json");b.setRequestHeader("D","shub")},data:JSON.stringify({email:c,name:a}),success:function(b,
d,e){loading(!1);$(".re-actions").prop("disabled",!1);200==e.status&&b.status?(showServerMessage(b.message,"success"),$("#verify_btn, #resend_btn, .re-otp-container").show(),$(".name-container, .re-email-container, #register_btn").hide(),startCountdown()):showServerMessage(b.message,"error")},error:function(b,d,e){loading(!1)},statusCode:{500:function(b){},401:function(b){}}})});$(document).on("click",".profile",function(){chrome.windows.create({url:chrome.runtime.getURL("devtools-panel/profile.html"),
type:"popup",height:500,width:600}).then(function(){}).catch(function(c){})});$(document).on("click",".logout-btn",function(){logout()});$(document).on("click",".home-login-btn",function(){document.querySelector(".container").style.display="none";document.querySelector("#register_form").style.display="block"});checkSessionId();$(document).on("click",".close-modal",function(){$("#three-modal").hide()});$(document).on("click",".device-close",function(){let c=parseInt($(this).attr("data-num")),a=document.getElementById("licence").value.trim();
if(""==a)return!1;$("#three-modal").hide();loading(!0);$("#submit_btn").prop("disabled",!0);$("#submit_btn").val("Please wait");$.ajax({method:"POST",url:endpoint+"user/remove",beforeSend:function(b){b.setRequestHeader("Content-type","application/json")},data:JSON.stringify({lk:a,num:c}),success:function(b,d,e){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");200==e.status&&b.status?(browserType.storage.local.set({ttlt:b.token}),ttlt=b.token,browserType.storage.local.set({data:b.data,
messages:b.messages},function(){showLoginScreen(!0);browserType.runtime.sendMessage({message:"loggedin"},function(f){})}),loginIssue()):($("#submit_btn").prop("disabled",!1),$("#submit_btn").val("Login"),browserType.storage.local.remove("ttlt"),$(".subscription-status").text(b.message).slideDown(),setTimeout(()=>{$(".subscription-status").slideUp()},5E3),-1<b.message.indexOf("Already")&&$("#three-modal").show())},error:function(b,d,e){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");
$(".invalid-error.invalid-credentails").text("Invalid credentials").slideDown();setTimeout(function(){document.getElementsByClassName("invalid-credentails")[0].style.display="none"},3E3)},statusCode:{500:function(b){},401:function(b){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");$(".invalid-error.invalid-credentails").text("Invalid credentials").slideDown();setTimeout(function(){document.getElementsByClassName("invalid-credentails").style.display="none"},3E3)}}})});
$(document).on("click","#close_btn",function(){document.querySelector(".container").style.display="block";document.querySelector("#register_form").style.display="none"});$(document).on("click","#forgot_pass",function(){$(".email-container, .forgetbtn, #open_login").show();$(".licence-container, #submit_btn, #forgot_pass").hide()});$(document).on("click","#open_login",function(){$(".email-container, .forgetbtn, #open_login").hide();$(".licence-container, #submit_btn, #forgot_pass").show()})});
function loading(c){c?$(".loading-view").show():$(".loading-view").hide()}function loginIssue(){window.location.reload();$(".container").slideDown(250);$("#register_form").slideUp(250);checkSessionId()}function logout(){chrome.storage.local.remove("ttlt",function(){checkSessionId()})}
function logoutUser(c){$(".patronRequest").children(":not(.after-login)").show();$(".patronRequest .after-login").hide();$.ajax({method:"get",url:endpoint+"user/logout",beforeSend:function(a){a.setRequestHeader("Content-type","application/json");a.setRequestHeader("Authorization","Bearer "+c)},success:function(a,b,d){},error:function(a,b,d){},statusCode:{500:function(a){},401:function(a){}}})}
function checkUser(c){$.ajax({method:"get",url:endpoint+"user/get-user-v2",beforeSend:function(a){a.setRequestHeader("Content-type","application/json");a.setRequestHeader("Authorization","Bearer "+c)},success:function(a,b,d){if(200==d.status&&a.status)if((isExpired=a.licenseExpired)&&$(".upgrate-lifetime").show(),$(".user-name").text("Hi, "+a.name||"User"),$(".renewsub").text(a.message),allow=a.licenseExpired?!1:!0,showPt(allow),a.showUpgrade)$(".upgrate-lifetime").show().off("click").on("click",
function(){window.open(a.upgradeUrl,"_blank")});else $(".upgrate-lifetime").hide();else logout()},error:function(a,b,d){logout()},statusCode:{500:function(a){logout()},401:function(a){logout()}}})}function showRegForm(){$("#register_btn, #register_back_btn, #login_btn").show()}
function showServerMessage(c,a="info"){const b=$(".server-message");switch(a){case "success":a="#2ec52e";break;case "error":a="#c55555";break;case "warning":a="orange";break;default:a="blue"}b.stop(!0,!0).text(c).css({color:a,"font-weight":"bold"}).slideDown(300);setTimeout(()=>{b.slideUp(300)},15E3)}chrome.runtime.onMessage.addListener(function(c,a,b){"logout"===c.message&&(logout(),setInterval(()=>{window.location.reload()},2E3))});
function openLoginForm(){const c=(new Date).toISOString().split("T")[0];chrome.storage.local.get("lastLoginOpenDate",function(a){(a=a.lastLoginOpenDate)&&a===c||$.ajax({method:"GET",url:endpoint+"user/regshow",beforeSend:function(b){b.setRequestHeader("Content-type","application/json");b.setRequestHeader("D","shub")},success:function(b,d,e){200==e.status&&b.status&&b.allowed&&($(".home-login-btn").click(),$("#show_reg_form").click(),$(".back-btn, .close-all").hide(),chrome.storage.local.set({lastLoginOpenDate:c}))},
error:function(b,d,e){},statusCode:{500:function(b){},401:function(b){}}})})}hitCounterApiIfDateChanged();
function hitCounterApiIfDateChanged(){const c=(new Date).toISOString().split("T")[0];chrome.storage.local.get(["user_counter_last_hit_date"],function(a){a.user_counter_last_hit_date!==c&&$.ajax({method:"GET",url:endpoint+"user/counter",beforeSend:function(b){b.setRequestHeader("Content-type","application/json");b.setRequestHeader("D","shub")},success:function(b){b={};b.user_counter_last_hit_date=c;chrome.storage.local.set(b,function(){})},error:function(b,d,e){},statusCode:{500:function(){},401:function(){}}})})}
;
